name: Developer Portal
highlighter: pygments
baseurl: /developerportal
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
webservices_baseurl: 'https://api.trade.gov'
apikey: 'd0lmowK8tvxPixAfm9sKOd_f'

left_nav_available_apis:
- text: Market Research Library
  url: market-research-library.html
- text: Consolidated Screening List
  url: consolidated-screening-list.html
- text: Trade Events
  url: trade-events.html
- text: Trade Leads
  url: trade-leads.html
- text: Tariff Rates
  url: tariff-rates.html
- text: FAQs on Exporting
  url: faqs-exporting.html
- text: ITA Offices & Centers
  url: ita-office-locations.html
- text: Trade News & Articles
  url: ita-trade-articles.html

mobile_nav_available_apis:
- text: Market Research Library
  url: market-research-library.html
- text: Consolidated Screening List
  url: consolidated-screening-list.html
- text: Trade Events
  url: trade-events.html
- text: Trade Leads
  url: trade-leads.html
- text: Tariff Rates
  url: tariff-rates.html
- text: FAQs on Exporting
  url: faqs-exporting.html
- text: ITA Offices & Centers
  url: ita-office-locations.html
- text: Trade News & Articles
  url: ita-trade-articles.html
  
mobile_nav_additional_resources:
- text: Guidance
  url: guidance.html
- text: Contact
  url: contact.html
- text: App Gallery
  url: app-gallery.html
- text: API FAQs
  url: api-faqs.html
- text: Change Log
  url: change-log.html
- text: Terms of Service
  url: tos.html
  
  
