name: Developer Portal
highlighter: pygments
baseurl: /developerportal
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
webservices_baseurl: 'https://api.govwizely.com'
apikey: 'Jnl2JctPOiUL9x7HVFR2m8Sr'

left_nav_available_apis:
- text: Market Research Library
  url: market-research-library.html
- text: Consolidated Screening List
  url: consolidated-screening-list.html
- text: Trade Events
  url: trade-events.html
- text: Trade Leads
  url: trade-leads.html
- text: Tariff Rates
  url: tariff-rates.html
- text: FAQs on Exporting
  url: faqs-exporting.html
- text: List of all APIs
  url: api-list.html


mobile_nav_available_apis:
- text: Market Research Library
  url: market-research-library.html
- text: Consolidated Screening List
  url: consolidated-screening-list.html
- text: Trade Events
  url: trade-events.html
- text: Trade Leads
  url: trade-leads.html
- text: Tariff Rates
  url: tariff-rates.html
- text: FAQs on Exporting
  url: faqs-exporting.html
- text: List of all APIs
  url: api-list.html
  
mobile_nav_additional_resources:
- text: Guidance
  url: guidance.html
- text: Contact
  url: contact.html
- text: App Gallery
  url: app-gallery.html
- text: API List
  url: api-list.html
- text: API FAQs
  url: api-faqs.html
- text: Change Log
  url: change-log.html
- text: Terms of Service
  url: tos.html
  
  
